### ISSUE TITLE
Investigate mathematically solving for optimal PID parameters

### ISSUE THREAD

**Issue by antoinedang** [mcgill-robotics/AUV-2025#210]

**Comment by MrMondrian** [comment]
What's the difference between this and https://github.com/mcgill-robotics/AUV-2024/issues/208? I don't think automatic pid tuning is a common thing

**Comment by antoinedang** [comment]
> What's the difference between this and #208? I don't think automatic pid tuning is a common thing

I put them as seperate things since once we solve for the dynamics of the AUV, we can apply that knowledge in many ways (from what I've understood). So this would represent solving for the dynamics of the model, and then we can plug it into matlab and solve for PID values quickly. Then the next step would be implementing the pole thing you wanted to try or other control methods. So i made them seperate cuz I see them as pretty seperate steps: first we solve the dynamics and keep PIDs but just make them better/adaptive, since that wouldn't require huge changes and we can test it instantly. Then we can add more complex control models after using the model we solved for
