### ISSUE TITLE
build docker images with buildx

### ISSUE THREAD

**Issue by MrMondrian** [mcgill-robotics/AUV-2025#614]
The images currently hosted [on docker hub](https://hub.docker.com/layers/mcgillrobotics/auv_2024/sim/images/sha256-5f4df156bcacbe9b2259ac83791fcb0fe132f054f68ef84cc596060eb05143ff?context=repo) are built only for amd64, but they need to be rebuilt for amd64 AND arm64 to accommodate mac users when they return. Only need to do this for base sim and poolside (in that order).

someone must've forgotten to use buildx at comp then pushed and since we all had amd64 machines no one noticed

instructions can be found [here](https://github.com/mcgill-robotics/AUV-2025/wiki/7.-Docker#cross-compiled-building)

**Comment by majdkhalife** [comment]
Its done.
I can write out steps for people and add it in the wiki in case this would happen again? What do you think

**Comment by MrMondrian** [comment]
Yes I agree, its a really easy mistake to make. Most peoples instincts is to either run `docker build` or `docker compose build` but neither invoke buildx

**Comment by MrMondrian** [comment]
It might be possible to get `docker compose build` to cross compile by using the platform option https://github.com/compose-spec/compose-spec/blob/main/spec.md#platform and passing `--builder` as a command line arguments to `docker compose build` but not sure if this is possible or really all that useful
